#!/usr/bin/env bash
# Installs libcairo2 1.16.0-2 for ubuntu

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

export DEBIAN_FRONTEND=noninteractive

case "$DOKKU_DISTRO" in
  debian|ubuntu)
    apt-get update
    apt-get install -y -qq gdebi

    wget http://launchpadlibrarian.net/405836989/libfreetype6_2.9.1-3_amd64.deb
    wget http://launchpadlibrarian.net/408231974/fontconfig-config_2.13.1-2ubuntu2_all.deb
    wget http://launchpadlibrarian.net/408231984/libfontconfig1_2.13.1-2ubuntu2_amd64.deb
    wget http://launchpadlibrarian.net/403060691/libcairo2_1.16.0-2_amd64.deb
    gdebi libfreetype6_2.9.1-3_amd64.deb --no-interaction
    gdebi fontconfig-config_2.13.1-2ubuntu2_all.deb --no-interaction
    gdebi libfontconfig1_2.13.1-2ubuntu2_amd64.deb --no-interaction
    gdebi libcairo2_1.16.0-2_amd64.deb --no-interaction
    ;;
esac
