#!/usr/bin/env bash
# Installs libcairo2 1.16.0-2 for ubuntu
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"
dokku_log_info1 "Installing cairo and dependencies"

DIR=/app

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get upgrade
apt-get install -y -qq gdebi

wget http://launchpadlibrarian.net/405836989/libfreetype6_2.9.1-3_amd64.deb
wget http://launchpadlibrarian.net/408231974/fontconfig-config_2.13.1-2ubuntu2_all.deb
wget http://launchpadlibrarian.net/408231984/libfontconfig1_2.13.1-2ubuntu2_amd64.deb
wget http://launchpadlibrarian.net/403060691/libcairo2_1.16.0-2_amd64.deb
gdebi libfreetype6_2.9.1-3_amd64.deb --no-interaction
gdebi fontconfig-config_2.13.1-2ubuntu2_all.deb --no-interaction
gdebi libfontconfig1_2.13.1-2ubuntu2_amd64.deb --no-interaction
gdebi libcairo2_1.16.0-2_amd64.deb --no-interaction

sleep 1 # wait so that docker run has not exited before docker attach
EOF
)

id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")

# Enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

dokku_log_verbose "done"